### ISSUE TITLE
django debug toolbar support.

### ISSUE THREAD

**Issue by alexdeathway** [alexdeathway/headstart-django#11]

**Comment by Dipec001** [comment]
Still open? Can you provide more details?

**Comment by Nexusrex18** [comment]
could you assign me this issue under hacktoberfest 24?

**Comment by alexdeathway** [comment]
@Dipec001 @Nexusrex18 after some considerations, came to the conclusion that Integrating Django Debug Toolbar would introduce unnecessary overhead when developing APIs, as it doesn't support API out of the box. Hence, closing the issue.
